UPDATE configuration SET maxspeed = CASE 
    WHEN tag_value = 'road'              THEN 20 -- Rare -- basically unclassified.
    WHEN tag_value = 'motorway'          THEN 70 -- Interstates
    WHEN tag_value = 'motorway_link'     THEN 40
    WHEN tag_value = 'motorway_junction' THEN 40 -- empty 
    WHEN tag_value = 'trunk'             THEN 55 -- Lake Shore Driver, major highways
    WHEN tag_value = 'trunk_link'        THEN 30 -- 
    WHEN tag_value = 'primary'           THEN 35 -- Commerical strips w/ stoplights.
    WHEN tag_value = 'primary_link'      THEN 40 -- 
    WHEN tag_value = 'secondary'         THEN 25 
    WHEN tag_value = 'tertiary'          THEN 25 
    WHEN tag_value = 'residential'       THEN 20 
    WHEN tag_value = 'living_street'     THEN 20 
    WHEN tag_value = 'service'           THEN 15 
    WHEN tag_value = 'track'             THEN 10 
    WHEN tag_value = 'pedestrian'        THEN 2 
    WHEN tag_value = 'services'          THEN 2 
    WHEN tag_value = 'bus_guideway'      THEN 2 
    WHEN tag_value = 'path'              THEN 5 
    WHEN tag_value = 'cycleway'          THEN 10 
    WHEN tag_value = 'footway'           THEN 2 
    WHEN tag_value = 'bridleway'         THEN 2 
    WHEN tag_value = 'byway'             THEN 2 
    WHEN tag_value = 'steps'             THEN 0.1 
    WHEN tag_value = 'unclassified'      THEN 5 
    WHEN tag_value = 'secondary_link'    THEN 20 
    WHEN tag_value = 'tertiary_link'     THEN 20 
    WHEN tag_value = 'lane'              THEN 10 -- Bikes 
    WHEN tag_value = 'track'             THEN 10 
    WHEN tag_value = 'opposite_lane'     THEN 10 
    WHEN tag_value = 'opposite'          THEN 10 
    WHEN tag_value = 'grade1'            THEN 10 
    WHEN tag_value = 'grade2'            THEN 10 
    WHEN tag_value = 'grade3'            THEN 10 
    WHEN tag_value = 'grade4'            THEN 10 
    WHEN tag_value = 'grade5'            THEN 10 
    WHEN tag_value = 'roundabout'        THEN 25 -- Almost none.
    ELSE 25
END;
